### ISSUE TITLE
Building giving erros , please ...help me ...

### ISSUE THREAD

**Issue by chaitusvk** [aut0/avp64#14]
In file included from /home/chaitusvk/Documents/systemc_libs/avp64/include/avp64/system.h:14,
                 from /home/chaitusvk/Documents/systemc_libs/avp64/src/main.cpp:10:
/home/chaitusvk/Documents/systemc_libs/avp64/include/avp64/arm64_cpu.h:75:15: error: ‘irq_initiator_socket_array’ in namespace ‘vcml’ does not name a template type; did you mean ‘i2c_initiator_socket_array’?
   75 |         vcml::irq_initiator_socket_array<> TIMER_IRQ_OUT;
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |               i2c_initiator_socket_array
make[2]: *** [CMakeFiles/avp64.dir/build.make:89: CMakeFiles/avp64.dir/src/main.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/chaitusvk/Documents/systemc_libs/avp64/include/avp64/system.h:14,
                 from /home/chaitusvk/Documents/systemc_libs/avp64/src/system.cpp:11:
/home/chaitusvk/Documents/systemc_libs/avp64/include/avp64/arm64_cpu.h:75:15: error: ‘irq_initiator_socket_array’ in namespace ‘vcml’ does not name a template type; did you mean ‘i2c_initiator_socket_array’?
   75 |         vcml::irq_initiator_socket_array<> TIMER_IRQ_OUT;
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |               i2c_initiator_socket_array
/home/chaitusvk/Documents/systemc_libs/avp64/src/system.cpp: In member function ‘void avp64::system::construct_system_arm64()’:
/home/chaitusvk/Documents/systemc_libs/avp64/src/system.cpp:41:26: error: ‘using element_type = class avp64::arm64_cpu’ {aka ‘class avp64::arm64_cpu’} has no member named ‘TIMER_IRQ_OUT’
   41 |             m_cpus[cpu]->TIMER_IRQ_OUT[avp64::ARM_TIMER_PHYS].bind(m_gic.ppi_in[irq_gt_ns-16+(cpu*16)]);
      |                          ^~~~~~~~~~~~~
/home/chaitusvk/Documents/systemc_libs/avp64/src/system.cpp:42:26: error: ‘using element_type = class avp64::arm64_cpu’ {aka ‘class avp64::arm64_cpu’} has no member named ‘TIMER_IRQ_OUT’
   42 |             m_cpus[cpu]->TIMER_IRQ_OUT[avp64::ARM_TIMER_VIRT].bind(m_gic.ppi_in[irq_gt_virt-16+(cpu*16)]);
      |                          ^~~~~~~~~~~~~
/home/chaitusvk/Documents/systemc_libs/avp64/src/system.cpp:43:26: error: ‘using element_type = class avp64::arm64_cpu’ {aka ‘class avp64::arm64_cpu’} has no member named ‘TIMER_IRQ_OUT’
   43 |             m_cpus[cpu]->TIMER_IRQ_OUT[avp64::ARM_TIMER_HYP].bind(m_gic.ppi_in[irq_gt_hyp-16+(cpu*16)]);
      |                          ^~~~~~~~~~~~~
/home/chaitusvk/Documents/systemc_libs/avp64/src/system.cpp:44:26: error: ‘using element_type = class avp64::arm64_cpu’ {aka ‘class avp64::arm64_cpu’} has no member named ‘TIMER_IRQ_OUT’
   44 |             m_cpus[cpu]->TIMER_IRQ_OUT[avp64::ARM_TIMER_SEC].bind(m_gic.ppi_in[irq_gt_s-16+(cpu*16)]);
      |                          ^~~~~~~~~~~~~
In file included from /home/chaitusvk/Documents/systemc_libs/avp64/src/arm64_cpu.cpp:10:
/home/chaitusvk/Documents/systemc_libs/avp64/include/avp64/arm64_cpu.h:75:15: error: ‘irq_initiator_socket_array’ in namespace ‘vcml’ does not name a template type; did you mean ‘i2c_initiator_socket_array’?
   75 |         vcml::irq_initiator_socket_array<> TIMER_IRQ_OUT;
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |               i2c_initiator_socket_array
/home/chaitusvk/Documents/systemc_libs/avp64/src/arm64_cpu.cpp: In member function ‘virtual void avp64::arm64_cpu::signal(ocx::u64, bool)’:
/home/chaitusvk/Documents/systemc_libs/avp64/src/arm64_cpu.cpp:128:9: error: ‘TIMER_IRQ_OUT’ was not declared in this scope
  128 |         TIMER_IRQ_OUT[sigid] = set;
      |         ^~~~~~~~~~~~~
/home/chaitusvk/Documents/systemc_libs/avp64/src/arm64_cpu.cpp: In constructor ‘avp64::arm64_cpu::arm64_cpu(const sc_core::sc_module_name&, vcml::u64, vcml::u64)’:
/home/chaitusvk/Documents/systemc_libs/avp64/src/arm64_cpu.cpp:373:11: error: class ‘avp64::arm64_cpu’ does not have any field named ‘TIMER_IRQ_OUT’
  373 |         , TIMER_IRQ_OUT("TIMER_IRQ_OUT")
      |           ^~~~~~~~~~~~~
make[2]: *** [CMakeFiles/avp64.dir/build.make:76: CMakeFiles/avp64.dir/src/system.cpp.o] Error 1
make[2]: *** [CMakeFiles/avp64.dir/build.make:63: CMakeFiles/avp64.dir/src/arm64_cpu.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:244: CMakeFiles/avp64.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by aut0** [comment]
CI is passing, so I assume the error is on your side. Check build procedure here:
https://github.com/aut0/avp64/blob/master/.github/workflows/cmake.yml

If you need further support, please describe what commands you executed.

**Comment by chaitusvk** [comment]
Sorry ,instead of git clone I just downloaded zip ....
