### ISSUE TITLE
co_simule with RTL in EDA with systemc TLM2.0

### ISSUE THREAD

**Issue by JohnVida** [aut0/avp64#44]
Hi
Is there an interface of TLM2.0 which can talk with RTL simulation in EDA?
and how aboult the simulation speeds of nature?

**Comment by aut0** [comment]
Hi,

Yes it is possible.
You can check my paper here: https://www.jngr.org/papers/juenger_erts2022.pdf
If you would like to have a more in-depth discussion, please send me an e-mail.

As this is not an issue with the simulator, I will close this topic here.

Best regards,
Lukas
