### ISSUE TITLE
No configuration file provieded

### ISSUE THREAD

**Issue by TheSSDGuy** [aut0/avp64#48]
Hello,

as described in the title, I'm trying to run the simulator with the following command:

`<install-dir>/bin/avp64-runner -f <install-dir>/sw/<config-file>`

but under my install-dir/sw I cannot find any configuration file. There is only a gitignore file.

Any suggestion?

Many thanks

**Comment by nbosb** [comment]
Hi,

avp64 does not provide any configuration files. Examples of target software can be found in the [avp64_sw](https://github.com/aut0/avp64_sw) repository. I have added information about this to the readme. Also, there is now a bash script that fetches the latest buildroot linux build from the avp64_sw repository, untars it, and places the files in the sw directory.

**Comment by aut0** [comment]
I assume this issue is resolved. If not, feel free to reopen.
