### ISSUE TITLE
the problem of asynchronous threads

### ISSUE THREAD

**Issue by MENGXICAT** [aut0/avp64#49]
Hello！
（defalut is false）When I use async("async", true) ，it seems to cause **memory misalignment** or **Error: (E519) wait() is only allowed in SC_THREADs and SC_CTHREADs**.How do I solve this problem？
Many thanks♪(･ω･)ﾉ

**Comment by reimannl** [comment]
![m3xp6szaqvua1](https://github.com/user-attachments/assets/8e0aa8cc-0813-4322-9ee1-1d4b5045ef4d)

**Comment by aut0** [comment]
Hi,

Thank you for your interest in avp64. Unfortunately, async is currently not supported.
Pull requests are welcome.

Best regards,
Lukas

**Comment by MENGXICAT** [comment]
ok!thanks you for your answer
