### ISSUE TITLE
 simulation performance of avp64

### ISSUE THREAD

**Issue by g-uooo** [aut0/avp64#50]
Hi
I would like to know the simulation performance of avp64, is there any performance data for instances built on avp64?
Thanks！

**Comment by aut0** [comment]
Hi g-uooo,

I think this is rather a question than an issue.
The simulator performance depends on several things:
- Host machine (e.g. high-performance workstation vs. laptop computer)
- Target software (e.g. bare-metal vs hypervisor workload)
- Simulation models (slowest model dominates performance)

To gauge the performance, I recommend to check the execution of the benchmarks included in the software package:
https://github.com/aut0/avp64_sw/tree/master/benchmark

**Comment by g-uooo** [comment]
> Hi g-uooo,
> 
> I think this is rather a question than an issue. The simulator performance depends on several things:
> 
> * Host machine (e.g. high-performance workstation vs. laptop computer)
> * Target software (e.g. bare-metal vs hypervisor workload)
> * Simulation models (slowest model dominates performance)
> 
> To gauge the performance, I recommend to check the execution of the benchmarks included in the software package: https://github.com/aut0/avp64_sw/tree/master/benchmark

Thank you for your reply!
I built a VP for storage acceleration based on Gem5 (emulating ARM), SystemC (emulating more than a dozen IPs, buses, memories, etc.), and QEMU (emulating hosts.) When dealing with FIO (I/O performance testing tool), its performance does vary when running on different hosts (PC and server), but the absolute performance is still low -- bandwidth is only a few tens of KB. after analyzing the tests, some data suggests that Gem5 is causing a degradation of the emulation performance. While avp64 can build VPs without Gem5, I'm wondering if there is a significant increase in emulation performance in this case? Any other relevant information would be of great help to my subsequent development.
Looking forward to your reply.

**Comment by aut0** [comment]
Without profiling the simulator, any conclusions about the bottleneck are just assumptions. In my experience, this often leads to optimizing the wrong areas. In general, gem5 is much slower at simulating CPUs than QEMU. It is a completely different technology and targets a different use case.

This topic falls outside the scope of the avp64 issue tracker. Feel free to reach out to me directly if you’d like to discuss it further.
